### ISSUE TITLE
Unable to run the basic 60s sample...

### ISSUE THREAD

**Issue by JeromeDaniel** [fetherston/npm-parrot-minidrone#17]
Hi,

I just discovered your project, this is really great !

I installed everything as mentioned, I have got a Parrot Minidrone Cargo.

When I run the demo, I got the following issue:

info: Searching for drones...
/Users/Jerome/Dev/MiniDrones/node_modules/parrot-minidrone/lib/MiniDroneBtAdapter.js:406
        const localNameMatch = matchesFilter || DRONE_PREFIXES.some((prefix) => localName.indexOf(prefix) >= 0);
                                                                                         ^

TypeError: Cannot read property 'indexOf' of undefined
    at DRONE_PREFIXES.some (/Users/Jerome/Dev/MiniDrones/node_modules/parrot-minidrone/lib/MiniDroneBtAdapter.js:406:90)
    at Array.some (native)
    at MiniDroneBtAdapter.validatePeripheral (/Users/Jerome/Dev/MiniDrones/node_modules/parrot-minidrone/lib/MiniDroneBtAdapter.js:406:64)
    at MiniDroneBtAdapter.onPeripheralDiscovery (/Users/Jerome/Dev/MiniDrones/node_modules/parrot-minidrone/lib/MiniDroneBtAdapter.js:315:19)
    at Noble.MiniDroneBtAdapter.noble.on (/Users/Jerome/Dev/MiniDrones/node_modules/parrot-minidrone/lib/MiniDroneBtAdapter.js:98:56)
    at emitOne (events.js:96:13)
    at Noble.emit (events.js:188:7)
    at Noble.onDiscover (/Users/Jerome/Dev/MiniDrones/node_modules/noble/lib/noble.js:137:10)
    at emitMany (events.js:127:13)
    at NobleBindings.emit (events.js:201:7)

Any idea ?

Thanks in advance for your help.

Jerome.

**Comment by JeromeDaniel** [comment]
I found the issue. It looks like I have many devices at home detected by the noble lib.
For some of them, there is no name given, so there is an undefined value for 'localName'.

I fixed the issue by adding on line 406:

if (localName === undefined) {
    return false;
}

Now, it works very well ! Thanks a lot for the lib.

**Comment by fetherston** [comment]
I've actually had this issue recently and will add this patch to the master branch soon.
