### ISSUE TITLE
Error on npm install parrot-minidrone

### ISSUE THREAD

**Issue by silgon** [fetherston/npm-parrot-minidrone#23]
Hello. I cannot get the installation part done. When I type `npm install parrot-minidrone` the following message appears.

```
make: Entering directory '/home/user/soft/drone/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
compilation terminated.
hidapi.target.mk:97: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
make: Leaving directory '/home/user/soft/drone/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/soft/drone/node_modules/node-hid
gyp ERR! node -v v9.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

Any ideas of how to get around this?

**Comment by silgon** [comment]
It compiles now. The thing is I installed `libusb-dev` but the libusb was not being detected. I installed `libusb-1.0-0-dev` and it compiled.
