### ISSUE TITLE
Where do I have to save the index.js file?

### ISSUE THREAD

**Issue by Rentex1** [fetherston/npm-parrot-minidrone#27]
Hi there!
I want to fly my Mambo with this package.
But when I run the index.js file an error appears and says:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'parrot-minidrone'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Luis/Documents/GitHub/npm-parrot-minidrone/index.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Where do I have to save my index.js file that it works?
Pls Help

**Comment by fetherston** [comment]
It sounds like you may of had an error with a dependency while running npm install and the parriot-minidrone package never made it into your node_modules folder. Try using NVM to downgrade node to 6.2.2 and run `npm install parrot-minidrone`. That said, I'm having issues with noble's dependencies on Mojave now. 

I may move this whole thing to docker as it's been difficult to maintain the dependencies this library uses.

**Comment by tyler-canton** [comment]
Sounds like you didn't install the parrot-minidrone module did you npm i
parrot-minidrone --save ?

**Comment by Rentex1** [comment]
Thanks!
I’ve noticed that when I run sudo npm install parrot-minidrone that there is an permission error. It says the permission was denied by my operating system.
How can I give it the write and read permission?
I already saw some people having the same trouble but I wasn’t able to get rid of it.
Thanks a lot!

**Comment by tyler-canton** [comment]
you should be able to chown your global node_module. Just google permission
issue of the directory the module is trying to write to...

**Comment by Rentex1** [comment]
Okay thanks now I don't have any troubles with permission but some other bigger troubles:

`1 warning generated.
  LIBTOOL-STATIC Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:207:45: error: no matching member function for call to 'NewInstance'
    Local<Object> buf = nodeBufConstructor->NewInstance(1, nodeBufferArgs);
                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:4108:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:4105:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/HID.cc:231:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  iocb->_callback->Call(2, argv);
                   ^
../../../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/HID.cc:363:61: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
    message.push_back((unsigned char) messageArray->Get(i)->Int32Value());
                                                            ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:404:35: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      int32_t vendorId = info[0]->Int32Value();
                                  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:405:36: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      int32_t productId = info[1]->Int32Value();
                                   ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:409:37: warning: 'Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
        serialPointer = (wchar_t*) *v8::String::Value(info[2]);
                                    ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:3016:5: note: 'Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version", explicit Value(Local<v8::Value> obj));
    ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:443:26: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
  blockStatus = info[0]->Int32Value();
                         ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:471:63: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      message.push_back((unsigned char) messageArray->Get(i)->Int32Value());
                                                              ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:535:27: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      vendorId = info[0]->Int32Value();
                          ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:536:28: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      productId = info[1]->Int32Value();
                           ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/Luis/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
`

I don't know what I have done wrong.

I don't know what to do with this either:
`enoent ENOENT: no such file or directory, open '/Users/Luis/package.json'
npm WARN Luis No description
npm WARN Luis No repository field.
npm WARN Luis No README data
npm WARN Luis No license field.`


I am sorry for taking your time.
I am a total beginner with using node.js.

**Comment by Rentex1** [comment]
thanks now all my troubles with the permission are solved but now there are many errors which say:
`warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
      productId = info[1]->Int32Value();
`
This occurs when I run `npm install parrot-minidrone`.

And in my `package.json` file the description,  repository field, license field and the Read.me data is missing. What do I have to add to my package.json file?

I am sorry for taking your time.
I am a total beginner in working with node.js and I am happy about any suggestion.
I have tried to adding this `"repository" : { 
   "type" : "git",
   "url" : "https://github.com/npm/npm.git"
 }` to my package.json file.
 But nothing went better.

**Comment by fetherston** [comment]
Warnings are generally okay. I wouldn't worry much about what's in your package.json except that after running `npm install --save parrot-minidrone` parrot-minidrone shows up under the `dependencies` key and you can see the library in your node modules folder (along with a pile of other stuff).

**NOTE XPC-CONNECTION FAILS OT INSTALL ON THE LATEST NODE LTS**
I've created a separate issue to track that: https://github.com/fetherston/npm-parrot-minidrone/issues/28. Idk how to fix that just yet as it's a dependency of a dependency (noble).

I just walked through the steps and was able to use the package with node v8.12.0. and npm v6.4.1 on OSX Mojave.

1. On a mac make sure you've installed xcode.
1. Make sure you're on node 8.12.0 (`node -v`). If not, [install and learn how to use nvm](https://github.com/creationix/nvm#installation), it's easy.)
1. Create a new folder for your node project and open it in terminal
1. Create a new npm package `npm init` and hit enter through all the steps
1. Install parrot-minidrone `npm install --save parrot-minidrone`
1. It should install with warnings but not errors
1. Create an index.js file [with the contents from the readme](https://github.com/fetherston/npm-parrot-minidrone#get-started-in-60-seconds).
1.  Run it `node index.js`

That's enough to at least get you running to write your own code. If you just want to fly some drones you may want to check out this entire repo from git and run [the examples in the example folder](https://github.com/fetherston/npm-parrot-minidrone#examples).

**Comment by Rentex1** [comment]
When I install the package then there is an error with the node-hid package.
It is using the @0.5.6 Version but I have installed the the @7.0.0 multiple times and deleted it again just to make sure it’s using the the right version but it is not.
In the package.json file, the @7.0.0 version is declared.

Hopefully this is my last trouble.

**Comment by Rentex1** [comment]
Sorry I meant@0.7.X

**Comment by Rentex1** [comment]
Thanks but now a new problem appeared:
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script.`

I have delete Node and npm and installed it again but nothin worked.
In the `package.json` file the the new version of node-hid is declared.
@0.7.6
I dont know what to do and it would be nice if you help me just that last time.
